branch-defaults:
  master:
    environment: z358z358-env
global:
  application_name: z358z358
  default_ec2_keyname: onininon
  default_platform: 64bit Amazon Linux 2015.03 v1.3.0 running PHP 5.5
  default_region: ap-northeast-1
  profile: eb-cli
  sc: git
